# Create web hosts based on docker image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-welcomepage
spec:
  selector:
    matchLabels:
      app: capstone-welcomepage
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-welcomepage
    spec:
      containers:
      - name: capstone-welcomepage
        image: reddeew/capstone-project
        imagePullPolicy: Always
        ports:
        - containerPort: 80