  
# Create Load balancer
apiVersion: v1
kind: Service
metadata:
  name: capstone-welcomepage
spec:
  selector:
    app: capstone-welcomepage
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer